# Generated by Django 3.1.5 on 2021-01-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210124_0608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
